name = "GenLib"
uuid = "e0fdd441-59bc-4b30-afdc-19bed4d9eb49"
authors = ["Gilles-Philippe Morin <gphmorin@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"

[compat]
CSV = "0.10"
DataFrames = "1"
DataStructures = "0.18"
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
